version: '3.1'

services:

  db:
    container_name: fastapi-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_DB: fastapi

  app:
    container_name: fastapi-app
    image: python:3.7.3-stretch
    working_dir: /code
    environment:
      database: fastapi
      username: fastapi
      password: fastapi
      host: db
      PYTHONPATH: /code
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ../:/code
    command: sh deployments/run.sh